import { Contact } from "./types";

export const defaultContacts: Contact[] = [
  {
    id: "emc-001",
    name: "Rajesh Kumar Singh",
    role: "Head",
    department: "Electrical",
    phone: "+919810000001",
    whatsapp: "+919810000001",
    email: "rajesh.singh@emcdigital.com",
    availability: "24/7",
    priority: "Critical",
    notes: "Emergency electrical fault & DG backup",
    createdAt: new Date().toISOString(),
  },
  {
    id: "emc-002",
    name: "Suresh Mehta",
    role: "Supervisor",
    department: "Plumbing",
    phone: "+919810000002",
    whatsapp: "+919810000002",
    email: "suresh.mehta@emcdigital.com",
    availability: "Business Hours",
    priority: "High",
    notes: "Water supply & drainage systems",
    createdAt: new Date().toISOString(),
  },
  {
    id: "emc-003",
    name: "Amit Sharma",
    role: "Engineer",
    department: "HVAC",
    phone: "+919810000003",
    whatsapp: "+919810000003",
    availability: "On-Call",
    priority: "High",
    notes: "Central AC, ventilation, clean room HVAC",
    createdAt: new Date().toISOString(),
  },
  {
    id: "emc-004",
    name: "Priya Nair",
    role: "Manager",
    department: "IT & Network",
    phone: "+919810000004",
    whatsapp: "+919810000004",
    email: "priya.nair@emcdigital.com",
    availability: "24/7",
    priority: "Critical",
    notes: "Network, servers, EMR system uptime",
    createdAt: new Date().toISOString(),
  },
  {
    id: "emc-005",
    name: "Vikram Tiwari",
    role: "Officer",
    department: "Security",
    phone: "+919810000005",
    whatsapp: "+919810000005",
    availability: "24/7",
    priority: "Critical",
    notes: "CCTV, access control, guard deployment",
    createdAt: new Date().toISOString(),
  },
  {
    id: "emc-006",
    name: "Deepa Verma",
    role: "Coordinator",
    department: "Housekeeping",
    phone: "+919810000006",
    whatsapp: "+919810000006",
    availability: "Business Hours",
    priority: "Normal",
    notes: "OT, ICU, ward sanitation protocols",
    createdAt: new Date().toISOString(),
  },
  {
    id: "emc-007",
    name: "Arun Biomedics",
    role: "Technician",
    department: "Biomedical",
    phone: "+919810000007",
    whatsapp: "+919810000007",
    email: "arun.bio@emcdigital.com",
    availability: "On-Call",
    priority: "Critical",
    notes: "Ventilators, defibrillators, infusion pumps",
    createdAt: new Date().toISOString(),
  },
  {
    id: "emc-008",
    name: "Mohan Lal Yadav",
    role: "Engineer",
    department: "Civil & Structural",
    phone: "+919810000008",
    whatsapp: "+919810000008",
    availability: "Business Hours",
    priority: "Normal",
    notes: "Structural repairs, flooring, false ceiling",
    createdAt: new Date().toISOString(),
  },
];
